name: python-slip10

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup python for ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: poetry install
      - name: Run tests for Python-${{ matrix.python-version }} with ${{ matrix.os }}
        run: poetry run pytest

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup python for ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: poetry install --only=dev
      - name: Run style check
        run: poetry run make style_check
