name: python-slip10

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installation (deps and package)
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt -r tests/requirements.txt
        python setup.py install
    - name: Test with pytest
      run: |
        pytest -vvv

  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run `black` on the source code
      run: |
        python -m pip install --upgrade pip
        pip install black
        python -m black --check slip10 tests

  coincurve_versions:
    strategy:
      matrix:
        coincurve-version: [15, 16, 17]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Testing with Coincurve ${{ matrix.coincurve-version }}
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt -r tests/requirements.txt
        pip install -I coincurve==${{ matrix.coincurve-version }}
        python setup.py install
